- README.md
- fido2-net-lib/AuthDataHelper.cs
- fido2-net-lib/OptionsResponse.cs
See also: https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication
> Initial support for Windows Hello

- fido2-net-lib/AuthDataHelper.cs
- fido2-net-lib/AuthenticatorAssertionResponse.cs
- fido2-net-lib/AuthenticatorAttestationResponse.cs
- fido2-net-lib/AuthenticatorResponse.cs
Started some cleanup and consolidation, emphasis on code reuse between attestation and assertion operations.
> Cleanup and consistency updates

- fido2-net-lib.Test/UnitTest1.cs
- fido2-net-lib/AuthDataHelper.cs
- fido2-net-lib/AuthenticatorAssertionResponse.cs
- fido2-net-lib/AuthenticatorAttestationResponse.cs
Lots more conformance tests are passing.  Attestation support for SafetyNet is implemented, TPM and Android Key are still partially implemented pending MDS parsing and some additional parsing efforts.  Some cleanup and comments also included.
> Finished SafetyNet attestation, and some other bits

- Fido2Demo/Controller.cs
- Fido2Demo/wwwroot/js/webauthn.js
- fido2-net-lib/AssertionOptions.cs
- fido2-net-lib/AuthenticatorAssertionResponse.cs
- fido2-net-lib/CredentialCreateOptions.cs
- fido2-net-lib/Fido2NetLib.cs
- fido2-net-lib/Fido2ResponseBase.cs
- fido2-net-lib/Objects/AssertionVerificationResult.cs
- Exception handling in Controller.cs (the diff for Controller.cs is weird, I just added try catch blocks to the methods)
- Created base class Fido2ResponseBase for error handling
- Handling returned errors in client JavaScript
- client JavaScript cleanup - moved successful swal() dialogs to proper place
- client JavaScript unification - similar workflow for all the fetch() calls
> Error handling + client JavaScript improvements

- README.md
> Add webauthn.io site to Read More

- fido2-net-lib.Test/EnumExtensionTest.cs
- fido2-net-lib/EnumExtensions.cs
- fido2-net-lib/Fido2NetLib.csproj
* Update Fido2NetLib.csproj to use latest C# language
* Add minimal test for ToEnum
> Refactor and improve ToEnum extension method

- fido2-net-lib.Test/EnumExtensionTest.cs
- fido2-net-lib/EnumExtensions.cs
> Fixes enum parsing with dashed values

- Src/AttestationFormat/Packed.cs
- Src/Objects/AttestedCredentialData.cs
- Src/Objects/AuthenticatorData.cs
- Src/Objects/CredentialPublicKey.cs
- Src/Objects/Extensions.cs
- Test/UnitTest1.cs
Continue redesign of AuthenticatorData and such, added tests for them as well as assertion positive path.
> Refactor AuthenticatorData, and subcomponents

- Demo/wwwroot/js/custom.register.js
- Demo/wwwroot/js/mfa.register.js
- Demo/wwwroot/js/passwordless.register.js
- Demo/wwwroot/js/usernameless.register.js
Authenaticator->Authenticator.
Same typo in 4 files.
> Fix minor typos in demo javascript

- CONTRIBUTING.md
- README.md
Created `CONTRIBUTING.md`. The contents of the file are the old contents of the Contributing section of the README, plus the contents of the style rules discussed in #87 
For the rules, I have tried to merge the different propositions found in #87. The simplest ones were added to the bullet list at the beginning. The others were added almost as-is.
> Created CONTRIBUTING.md

- CHANGELOG.md
- README.md
Firstly thanks for the great project. I think it would help if this project had a changelog, and made it easier to find when what was released and where you can find the nugets, releases. This PR should help the visibility a small bit. 
I think also it would be great if you added release tags for the public releases. (Version 1.0.1 and Version 1.1.0) Then you could create a github release in your repo using the release tab from this repo. Since you don't release so often, you can do this manual, or course this could be automated using your pipeline. 
Just some ideas, 
Thanks for the project.
Greetings Damien
> Adding a changelog, and 2 links to the readme

- .github/workflows/verify-pr-label.yml
Adds a automatic check/review for required labels. The labels are used to generate better release notes.
The labels used are:
* breaking change
* bug
* enhancement
* feature
* chore
* documentation
And will output changes under different categories on the release notes. This will also help to decide SemVer versions as requested in #149
> Require labels on PR for better release notes

- Src/Fido2/AuthenticatorResponse.cs
Reverts abergs/fido2-net-lib#208.  Needs further testing.
> Revert "change origin verify to use fully qualified origin"

- Src/Fido2/AuthenticatorResponse.cs
see also https://github.com/duo-labs/webauthn/pull/60
> change origin verify to use fully qualified origin

- Directory.Build.props
- Fix fully qualified origin, add unit tests @aseigler (#217)
> Release 2.0.1

- Directory.Build.props
Reason is release the patch for the MDS new root cert.
> Release v2.0.2

- Src/Fido2/AuthenticatorAttestationResponse.cs
- Test/Attestation/Apple.cs
- Test/AuthenticatorResponse.cs
- Test/Fido2Tests.cs
Enforce UV in attestation if required for application registration, add tests for same
Resolves #275
> Enforce UV in attestation if required for registration

- .editorconfig
- Demo/Controller.cs
- Demo/TestController.cs
- Src/Fido2.AspNet/DistributedCacheMetadataService.cs
- Src/Fido2.AspNet/NullMetadataService.cs
- Src/Fido2/AttestationFormat/Tpm.cs
- Src/Fido2/AuthenticatorAssertionResponse.cs
- Src/Fido2/AuthenticatorAttestationResponse.cs
- Src/Fido2/DevelopmentInMemoryStore.cs
- Src/Fido2/Fido2NetLib.cs
- Src/Fido2/IFido2.cs
- Src/Fido2/IMetadataRepository.cs
- Src/Fido2/IMetadataService.cs
- Src/Fido2/Metadata/ConformanceMetadataRepository.cs
- Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs
- Src/Fido2/Metadata/FileSystemMetadataRepository.cs
- Src/Fido2/SimpleMetadataService.cs
- Test/Attestation/Apple.cs
- Test/Attestation/Tpm.cs
- Test/AuthenticatorResponse.cs
- Test/ExistingU2fRegistrationDataTests.cs
- Test/Fido2Tests.cs
- Test/MetadataServiceTests.cs
This PR adds `cancellationToken` parameters to Task methods.
Resolves #271
> Add CancellationToken to Task methods

- Src/Fido2.Models/Objects/AttestationVerificationSuccess.cs
- Src/Fido2/AuthenticatorAttestationResponse.cs
Expose the optional attestation certificates in the attestation response to store and/or inspect them further.
Fixes #299
> Expose attestation certificates in attestation response.

- Directory.Build.props
- v3.0.0-beta6
- Release 3.0.0
> Bump version to 3.0.0

- README.md
- VDP.md
This the the first time I've written a VDP.
I appreciate any feedback to make sure the VDP is easy to engage with and understand and covers "best practices"
> Added draft of Vulnerability Disclosure Program

- Demo/Pages/usernameless.cshtml
- Demo/UrlHelperExtensions.cs
Link to the demos were broken.
> fix: usernameless demos

- Src/Fido2/AttestationFormat/AppleAppAttest.cs
- Test/Fido2Tests.cs
There are three failing tests on Mac/Linux right now. This fixes one of them.
> Fix TestAppleAppAttestProd test on macOS & Linux

- Src/Fido2/Metadata/ConformanceMetadataRepository.cs
- Test/Test.csproj
They certinfa url was updated. This PR updates the url and improves the error message if it goes down in the future. This PR also updates the test dependencies to their latest versions.
@abergs @aseigler Ready for review!
Also, congratulations on the BitWarden acquisition!
> Fix Conformance Test

- Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs
> Add .bool to Output aswell

- BlazorWasmDemo/Server/Controllers/UserController.cs
- Demo/Controller.cs
- Src/Fido2.Development/StoredCredential.cs
> Use DateTimeOffset

- .github/workflows/main.yml
- azure-pipelines.yml
Updates the SDK from .NET7.0 -> 8.0 (LTS)
> Use net8.0 SDK

- README.md
- nuget.config
This pull request fixes the build, because the signatures for some packages have changed.
[https://devblogs.microsoft.com/nuget/the-nuget-org-repository-signing-certificate-will-be-updated-as-soon-as-april-8th-2024/](https://devblogs.microsoft.com/nuget/the-nuget-org-repository-signing-certificate-will-be-updated-as-soon-as-april-8th-2024/)
> NuGet.org signatures have been updated - Fix Build

- Demo/wwwroot/js/custom.login.js
- Demo/wwwroot/js/custom.register.js
- Demo/wwwroot/js/mfa.login.js
- Demo/wwwroot/js/mfa.register.js
- Demo/wwwroot/js/passwordless.login.js
- Demo/wwwroot/js/passwordless.register.js
- Demo/wwwroot/js/usernameless.login.js
- Demo/wwwroot/js/usernameless.register.js
As it looks like https://github.com/passwordless-lib/fido2-net-lib/pull/535 is tacking too long to make requested changes, here is another PR with (hopefully) fully functional demo site.
Fixes https://github.com/passwordless-lib/fido2-net-lib/issues/534
> Fixing demo project makeAssertionOptions.status processing

- README.md
Update README.md - Medium link was broken, now fixed.
> README.md Medium link fixed

- .github/workflows/main.yml
I also updated the other actions, hope everything is in order.
> Update Github actions

- .github/workflows/main.yml
- **Allow github push to fail while pushing to nuget**
- **Force release option**
> fix nuget force

- README.md
The changes in this commit update the README file with the following improvements:
1. Update the build status and code coverage badges to point to the `main` branch instead of `master`.
2. Remove the release and changelog link from the main section and move it to the bottom.
3. Add installation instructions for the core library, ASP.NET Core helpers, and Blazor WebAssembly support.
4. Update the "What is FIDO2?" section to provide a more concise and up-to-date description of the FIDO2/WebAuthn standard and its benefits.
These changes aim to provide a more informative and user-friendly README for the FIDO2 .NET Library.
> feat(readme): Update README with latest changes

- Src/Fido2/Metadata/FileSystemMetadataRepository.cs
To help indicaite that we want a directory
> Rename path argument to directoyPath
