fido2-net-lib/AuthDataHelper.cs, fido2-net-lib/AuthenticatorAssertionResponse.cs, fido2-net-lib/AuthenticatorAttestationResponse.cs, fido2-net-lib/DateTimeExtensions.cs, fido2-net-lib/Fido2NetLib.csproj, fido2-net-lib/TPM.cs
Proposing changing the fido2-net-lib project type to .NET Standard. It requires little change in code and the lib would be referenceable in all .NET implementations (see also [.NET Standard documentation](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)).
=> Convert fido-net-lib from .NET Core 2.1 to .NET Standard 2.0

Fido2Demo/Controller.cs, Fido2Demo/Fido2Demo.csproj, Fido2Demo/TestController.cs, fido2-net-lib.Test/UnitTest1.cs, fido2-net-lib/AuthenticatorAttestationResponse.cs, fido2-net-lib/Fido2NetLib.cs, fido2-net-lib/MetadataService.cs
A concept for swappable MDS.
This implementation is "unsafe but easy" by default. The default constructor of Configuration sets the MetdataService to null which is unsafe, but easy to get started.
I'm wondering if this is OK, given that we make it very clear in all examples / documents that you should set the Metadataservice (as shown in the examples in this PR).
I also changed the name of the AppSecrets to follow the standard used by our other variables.
=> Swappable MDS

docs/NET46X.md, fido2-net-lib/Fido2NetLib.csproj, fido2-net-lib/build/fido2.targets
Because of compatibility issues with .NET Standard 2.0 we have to make sure
there is a sane way for customers to learn that this package does not work with
.NET Framework 4.6.X Skus.
=> Added a guarding mechanism to prevent usage in .NET46X

fido2-net-lib.Test/fido2-net-lib.Test.csproj
Running ```dotnet test`` generates a bunch of errors if net462 is targeted.
=> Removed net462 from test project

fido2-net-lib/Fido2NetLib.csproj
A pending PR. Allows building in macOS and Linux otherwise, the compiler will argue about the missing .NET Framework 4.7.2 SDK in those platforms.
=> Support Target Frameworks by OS

Src/AuthenticatorAssertionResponse.cs, Test/ExistingU2fRegistrationDataTests.cs
https://www.w3.org/TR/webauthn/#sctn-appid-extension
> If true, the AppID was used and thus, when verifying an assertion, the Relying Party MUST expect the rpIdHash to be the hash of the AppID, not the RP ID.
=> use AppId instead of RpId to hash when AppId-Extensions-Flag is set

Demo/wwwroot/js/usernameless.login.js
For the usernamaless result on the client side, the **userHandle** was missing in the reply. 
This can be _nullable_, but not missing since it is even backwards compatible according to: https://www.w3.org/TR/webauthn/#conforming-authenticators-u2f
however: FIDO2 BtB (by the book ;-)
Quote from: 
https://www.w3.org/TR/webauthn/#discover-from-external-source 
step: "->If any authenticator indicates success."
**userHandleResult**
If the authenticator returned a _user handle_, set the value of **userHandleResult** to be the bytes of the returned user handle. Otherwise, set the value of **userHandleResult** to **null**.
I'm no .NET guy, so haven't checked what impact this field has on the backend when it suddenly appears. I presume 'nothing' but not sure. If someone else could please test that …
=> Add field userHandle in verifyAssertionWithServer

Demo/wwwroot/js/custom.register.js
I just changed the catched error variable from "e" to "err", so it gets used in the line below to show the error message.
=> corrected error variable

Src/Fido2/AttestationFormat/AttestationFormat.cs, Src/Fido2/AttestationFormat/Tpm.cs
The comparison for the X509BasicConstraintsExtension and the Extended Key Usage 2.23.133.8.3 doesn't work when the OS is not in English (usage of FriendlyName). I have fixed and validated with the units tests.
I have also added missing using blocks
=> Problem with non English OS

Test/UnitTest1.cs
Corresponds to recent conformance tool change in EdDSA signature validation handling.
=> EdDSA test, sign the actual data, not a hash of the data

Demo/TestController.cs, Src/Fido2/AttestationFormat/AndroidKey.cs, Src/Fido2/AttestationFormat/FidoU2f.cs, Src/Fido2/AttestationFormat/Packed.cs, Src/Fido2/AttestationFormat/Tpm.cs, Src/Fido2/AuthenticatorResponse.cs, Src/Fido2/CryptoUtils.cs, Src/Fido2/Objects/CredentialPublicKey.cs
Resolves #70. Plus other cross-platform issues, mostly related AsnEncodedData working differently on Windows vs non-Windows.  Some ECCurve related things should be revisited if we move to .NET Core 3.
=> Remove CNG dependencies to allow cross platform scenarios

Src/Fido2/AuthenticatorAssertionResponse.cs
Change: expose authenticator assertion response parse method to allow direct usage. Also removed unused credential id property.
Thank you for sharing this implementation! 
From API design perspective there is a bit of room for improvement. In my specific case I can't comfortable use the Fido2 class since it relies on a Fido2Configuration (which I need to generate per request due to the multi-tenant nature of my app) and it also generates a challenge which we want to handle our self (funny comment in code: // note: I have no idea if this crypto is ok...). For authenticator registration it worked fine to by-pass the Fido2 class but not for authentication due to the internal Parse method modified in this request. 
I took the opportunity to remove the confusing CredentialId property. …
=> Improved API consistency for response parsing

README.md
Should consider changing the library API to avoid the risk of API consumers making the same mistake.
Ideally consuming (reading and deleting) the challenge should be atomic, utilizing a transaction or similar.
I'm by no means a security expert so I might have missed something here.
=> Fixed challenge replay attack issue in examples

Demo/wwwroot/js/passwordless.register.js, Demo/wwwroot/js/usernameless.register.js
The `require_resident_key` property does not work properly unless it is a string.  This PR fixes that bug.  Tested with Chrome on Windows 10.
=> Bug fix: require_resident_key

Demo/Startup.cs, Demo/appsettings.json, Src/Fido2.Models/Fido2Configuration.cs, Src/Fido2/AttestationFormat/FidoU2f.cs, Src/Fido2/AttestationFormat/Packed.cs, Src/Fido2/AttestationFormat/Tpm.cs, Src/Fido2/AuthenticatorAttestationResponse.cs
As discussed in #159 and #158, this adds a configurable flag to validate that the root certificate matches a known root. This applies to TPM, Packed and U2F attestation formats.
To be honest, I think this should always be on, particularly for Packed and U2F. The code really seems to imply that the validation has occurred as this is implemented within the metadata verification. TPM is more tricky since the attestation root situation sucks for TPM. I'll submit a separate PR to hopefully improve that.
=> Add optional validation of attestation root certs

Demo/Startup.cs, Src/Fido2/AttestationFormat/AndroidSafetyNet.cs, Test/Attestation/AndroidSafetyNet.cs, Test/Attestation/Tpm.cs, Test/Fido2Tests.cs
- Related to #153, SafetyNet attestation verification broke when System.IdentityModel.Tokens.Jwt was updated.  Fixed in similar fashion.
- Refactor SafetyNet attestation verification
- Add SafetyNet attestation verification unit tests
- All 172 conformance tests pass with conformance tool version 1.3.4.
=> Fix SafetyNet attestation verification, add unit tests

nuget.config
Fixes broken CI/CD build by adding nuget.config file
https://developercommunity.visualstudio.com/content/problem/983843/dotnet-build-task-does-not-use-nugetorg-for-one-pr.html
=> Solve CI/CD Missing packages error

Src/Fido2/AttestationFormat/Packed.cs
When comparing two DateTimes, the `Kind` attribute is ignored, so comparing an UTC DateTime and a local DateTime do not give the expected result.
While the validity period is encoded as UTC in the certificate itself, it is converted to local time before it is returned in the X509Certificate2.NotBefore / X509Certificate.NotAfter attributes. This means that if we want to check whether the certificate is currently valid, we should compare it with the current _local_ time.
Fixes: #185
=> Compare certificate validity period correctly when the machine is using a time zone other than UTC

Src/Fido2/AuthenticatorResponse.cs
A Huawei P40 Lite sets the origin on register or sign in to https://www.passwordless.dev/custom#heroFoot and the verification fails.
With this PR,  the fully qualified origins are compared. see also https://github.com/duo-labs/webauthn/pull/60
=> change origin verify to use fully qualified origin

Demo/Startup.cs, Src/Fido2.AspNet/DistributedCacheMetadataService.cs, Src/Fido2.Models/Metadata/MetadataTOCPayload.cs, Src/Fido2/IMetadataRepository.cs, Src/Fido2/Metadata/ConformanceMetadataRepository.cs, Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs, Src/Fido2/Metadata/FileSystemMetadataRepository.cs, Src/Fido2/Metadata/StaticMetadataRepository.cs, Src/Fido2/SimpleMetadataService.cs, Test/MetadataServiceTests.cs
Improved error handling and logging for MDS errors along with a refactoring of how the TOC JWT alg is passed around to better serve the cached use-case.
The the TOC alg now gets stored in the MetadataTOCPayload class which is now passed into GetMetadataStatement. This means that it's possible to use a cached MetadataTOCPayload not created by the current IMetadataRepository instance.. 
Together these changes mean that an incident like we had with the Yubico version number won't cause the app startup to fail and will be recoverable even if the TOC is already cached.
This change will require anyone using the DistributedCacheMetadataService to clear their cache when upgrading to 2.0.
=> MDS error handling and cache-friendlieness refactoring

Src/Fido2.Models/Fido2MetadataException.cs, Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs
The FIDO Alliance have recently changed the root certificate for their Metadata Service table of contents (TOC).  The certificates in the TOC certificate chain have also changed from being ECC to RSA.  This branch contains the new TOC root certificate and support for RSA in addition to ECC keys in the intermediate and signing certificates within the X5c data.
=> Intercede FIDO md2 new TOC root cert

Src/Fido2/AttestationFormat/AndroidKey.cs, Src/Fido2/AttestationFormat/AndroidSafetyNet.cs, Src/Fido2/AttestationFormat/Apple.cs, Src/Fido2/AttestationFormat/AttestationFormat.cs, Src/Fido2/AttestationFormat/FidoU2f.cs, Src/Fido2/AttestationFormat/Packed.cs, Src/Fido2/AttestationFormat/Tpm.cs, Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Src/Fido2/Cbor/CborObject.cs, Src/Fido2/DateTimeHelper.cs, Src/Fido2/Extensions/DataHelper.cs, Src/Fido2/Metadata/ConformanceMetadataRepository.cs, Src/Fido2/Objects/AttestedCredentialData.cs, Src/Fido2/Objects/CredentialIdUserHandleParams.cs, Src/Fido2/Objects/CredentialIdUserParams.cs, Src/Fido2/Objects/CredentialPublicKey.cs, Test/Attestation/AndroidSafetyNet.cs, Test/Attestation/Apple.cs, Test/Attestation/Tpm.cs, Test/ExistingU2fRegistrationDataTests.cs, Test/Fido2Tests.cs
- Minor formats
- Use CborMap overloads to reduce casting
- Use init properties
- Improve X509Certificate2 construction from x5c arrays
- Construct trustRoot sooner, to reuse X509Certificate2 instance
- Update CredentialPublicKey constructor to use COSE.Algorithm 
- Use built-in DateTimeOffset.UnixEpoch
=> Improve Code Quality 5

README.md
Updated readme, replacing github.com/abergs to the new organisations, github.com/passwordless-lib
=> Fix old links in readme

Src/Fido2/AttestationFormat/Packed.cs, Src/Fido2/AttestationFormat/Tpm.cs, Src/Fido2/CryptoUtils.cs, Src/Fido2/Metadata/ConformanceMetadataRepository.cs, Test/Attestation/Tpm.cs, Test/Fido2Tests.cs
- Eliminates HashAlgorithm allocations
- Makes CryptoUtils internal (to allow for future optimizations)
- Replaces CompareTo with Equals 
- Seals Packed AttestationVerifier
- Fix member visibility warning
=> Improve Code Quality 7

Demo/.config/dotnet-tools.json, Demo/Demo.csproj, Demo/Pages/custom.cshtml, Directory.Build.props, Src/Fido2.AspNet/Fido2.AspNet.csproj, Src/Fido2.Models/Fido2.Models.csproj, Src/Fido2.Models/Fido2Configuration.cs, Src/Fido2/AttestationFormat/AndroidSafetyNet.cs, Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/Cbor/CborMap.cs, Src/Fido2/Fido2.csproj, Src/Fido2/Metadata/ConformanceMetadataRepository.cs, Test/.config/dotnet-tools.json, Test/Attestation/Apple.cs, Test/AuthenticatorResponse.cs, Test/Fido2Tests.cs, Test/Test.csproj, azure-pipelines.yml
Hi, there is already the .Net6 framework.
I prepared this small PR that adds it right next to the .Net5.
I found (and [resolved](https://github.com/trejjam/fido2-net-lib/commit/079b2e38f17cdab8be488e1f97c241d6681470e2)) one deprecation in packages: https://github.com/aspnet/Announcements/issues/303
=> Add .Net 6 as supported framework

Src/Fido2.Models/Base64Url.cs, Test/Base64UrlTest.cs
FIDO Conformance Tools section Server-ServerAuthenticatorAttestationResponse-Resp-1, test F-3 Send ServerAuthenticatorAttestationResponse sends illegally formatted base64url data for "id" field and expects failure.  We were ignoring the return value from Base64.DecodeFromUtf8InPlace(), so we were not detecting this condition.  This PR aligns us with what Convert.FromBase64CharArray() would throw given the same input string.
=> Check return value from Base64.DecodeFromUtf8InPlace(), throw if error

Test/Attestation/None.cs, Test/Attestation/Packed.cs, Test/Fido2Tests.cs, azure-pipelines.yml
Historically there have been several times where we've discovered code changes or test additions that work just fine on Windows, but are broken on Mac or Linux.  This PR should help proactively fill that gap by:
- Marking existing demo/test/coverage jobs to make it clear they are Windows specific
- Adding job to test Mac and Linux
- Updating tests where there are known/expected runtime issues
=> Add Mac and Linux to test pipeline

Src/Fido2.Models/Fido2Configuration.cs, Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/AuthenticatorResponse.cs
=> Fixes Fido2Configuration.FullyQualifiedOrigins contains a null entry when configured from a configuration section on .NET 7

Src/Fido2/AttestationFormat/AndroidSafetyNet.cs, Src/Fido2/AttestationFormat/FidoU2f.cs, Src/Fido2/AttestationFormat/Packed.cs, Src/Fido2/Extensions/IBufferWriterExtensions.cs, Src/Fido2/Extensions/JsonElementExtensions.cs, Src/Fido2/Extensions/X509CertificateHelper.cs, Src/Fido2/Metadata/ConformanceMetadataRepository.cs, Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs, Src/Fido2/Objects/AttestedCredentialData.cs, Src/Fido2/Objects/AuthenticatorData.cs, Src/Fido2/Objects/Extensions.cs, Test/Attestation/AndroidSafetyNet.cs
This PR:
- Consolidates the X509Certificate constructor / error handlers in X509CertificateHelper. We now throw an improved error message if there was invalid Base64 data.
- Uses the built-in JSON converter to decode base64 data. System.Text.Json can convert directly from the utf-8 bytes using the vectorized Base64 converter.
- Replaces the BinaryWriter with BufferWriter
=> Improve Code Quality

Demo/Controller.cs, Src/Fido2.AspNet/DistributedCacheMetadataService.cs, Src/Fido2.Models/Metadata/MetadataBLOBPayloadEntry.cs, Src/Fido2.Models/Metadata/MetadataStatement.cs, Src/Fido2.Models/Objects/AttestationVerificationSuccess.cs, Src/Fido2/AttestationFormat/AttestationVerifier.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Src/Fido2/ConformanceMetadataService.cs, Src/Fido2/Extensions/IBufferWriterExtensions.cs, Src/Fido2/Metadata/FileSystemMetadataRepository.cs, Test/Attestation/AndroidKey.cs, Test/Attestation/AndroidSafetyNet.cs, Test/Attestation/FidoU2f.cs, Test/Attestation/None.cs, Test/Attestation/Packed.cs, Test/Attestation/Tpm.cs, Test/Fido2Tests.cs, Test/MetadataServiceTests.cs
This PR updates AaGuid fields from a string to a Guid. This eliminates some allocations and the need to parse the Guid later.
Making as a draft until mds3.certinfra.fidoalliance.org goes back online and tests are green.
=> Strongly type AaGuid

Directory.Build.props, Src/Directory.Build.props, Src/Fido2.AspNet/Fido2.AspNet.csproj, Src/Fido2.Ctap2/Fido2.Ctap2.csproj, Src/Fido2.Models/Fido2.Models.csproj, Src/Fido2/Fido2.csproj, fido2-net-lib.sln
So I just spent hours figuring out why my build wanted to include some beta version of SourceLink and why all the references in the libraries are set to "Update". 
Turns out there's another Directory.Build.props I didn't see because I didn't look in the actual file system.  
This change makes it more obvious what's going on and also updates the SourceLink reference in the Directory.Build.props so the projects don't have to do it themselves.
Edit: The GUID change is just VS migrating from the old project system to the new one (see https://github.com/dotnet/project-system/issues/3079)
=> SourceLink consolidation

Src/Fido2.Models/Converters/EnumNameMapper.cs, Src/Fido2.Models/CredentialCreateOptions.cs, Src/Fido2.Models/Objects/AttestationConveyancePreference.cs, Src/Fido2.Models/Objects/AuthenticatorAttachment.cs, Src/Fido2.Models/Objects/AuthenticatorTransport.cs, Src/Fido2.Models/Objects/PublicKeyCredentialType.cs, Src/Fido2.Models/Objects/ResidentKeyRequirement.cs, Src/Fido2.Models/Objects/UserVerificationRequirement.cs, Src/Fido2/Extensions/EnumExtensions.cs, Test/EnumExtensionTest.cs
This PR:
- Removes support for enforcing the case sensitivity of the Enum parser. Enum parsing has always been case insensitive in the library.
- Update various references to a draft webauthn specification to the final published specification.
=> Simplify enum mapping & update specification links

Demo/TestController.cs, Src/Fido2.Models/Fido2Configuration.cs, Src/Fido2/AuthenticatorResponse.cs
=> Make Origins readonly

Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsPRFInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsPRFOutputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsPRFValues.cs, Test/AuthenticatorResponse.cs
This PR adds support for the [PRF extension](https://w3c.github.io/webauthn/#dictdef-authenticationextensionsprfvalues) to the extension client input/output models. 
All existing tests pass, but I am not sure if/what new tests need to be added for PRF support in this library.
=> Support for PRF Extension

Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs
expected value:
`{"example.extension.bool":true}`
Actual current value:
`{"example.extension":true}`
This fixes the first test:
`[Server-ServerPublicKeyCredentialCreationOptions-Req-1 Test server generating ServerPublicKeyCredentialCreationOptionsRequest](https://github.com/Applications/FIDO%20Alliance%20-%20Certification%20Conformance%20Testing%20Tools.app/Contents/Resources/app.asar/app/index.html?grep=%0A%0A%20%20%20%20%20%20%20%20Server-ServerPublicKeyCredentialCreationOptions-Req-1%0A%0A%20%20%20%20%20%20%20%20Test%20server%20generating%20ServerPublicKeyCredentialCreationOptionsRequest%0A%0A%20%20%20%20)`
=> Fix AuthenticationExtensionsClientInputs Example json prop name for conformance tests

Src/Fido2.Models/Objects/AttestationVerificationSuccess.cs, Src/Fido2/AttestationFormat/AndroidKey.cs, Src/Fido2/AttestationFormat/Apple.cs, Src/Fido2/AttestationFormat/AppleAppAttest.cs, Src/Fido2/AttestationFormat/AttestationVerifier.cs, Src/Fido2/AttestationFormat/FidoU2f.cs, Src/Fido2/AttestationFormat/Packed.cs, Src/Fido2/AttestationFormat/Tpm.cs, Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Src/Fido2/AuthenticatorResponse.cs, Src/Fido2/Fido2.csproj, Src/Fido2/Objects/AuthenticatorData.cs, Src/Fido2/Objects/CredentialIdUserHandleParams.cs, Src/Fido2/Objects/CredentialIdUserParams.cs, Test/Asn1Tests.cs, Test/Attestation/Tpm.cs, Test/AuthenticatorDataTests.cs, Test/AuthenticatorResponse.cs, Test/Fido2Tests.cs, Test/Test.csproj, Tests/Fido2.Ctap2.Tests/Fido2.Ctap2.Tests.csproj
This PR prevents the mutation of AuthenticatorData after parsing, and strongly types it throughout the library.
Ready for review.
=> [WIP] Make AuthenticatorData immutable and strongly type throughout library

Src/Fido2.Models/CredentialCreateOptions.cs
Because ED25519 is one of the top recommended public-key algorithms today.
=> Prefer Ed25519 when available

Demo/Controller.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Src/Fido2.Models/Objects/CredentialPropertiesOutput.cs
Browsers respond with a a object.
- Add CredentialPropertiesOutput
- Use .ID instead of null CredentialId
=> Add CredentialPropertiesOuput (RK Support)

Src/Fido2/Extensions/X509CertificateHelper.cs, Src/Fido2/Fido2.csproj, Src/Fido2/Metadata/ConformanceMetadataRepository.cs, Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs, azure-pipelines.yml
Is a bit faster to parse UTF-8 data directly than convert from UTF-16. 
NOTE, this uses the built-in support for static data initialization. Accessing ROOT_CERT is non-allocating and refers directly to the data.
This PR also simplifies a check using C# 11 list patterns.
=> Enable C# 11 and embed base64 encoded certificates as UTF-8 data

Src/Fido2.Ctap2/Extensions/PubKeyCredParamExtensions.cs, Src/Fido2.Models/Objects/AuthenticatorTransport.cs
Windows now natively supports hybrid (smartphone QR) transport.
https://w3c.github.io/webauthn/#enum-transport
Edit: fixes https://github.com/passwordless-lib/fido2-net-lib/issues/325
=> Add smart-card and hybrid transports

Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Test/AuthenticatorResponse.cs, Test/Fido2Tests.cs
=> Remove AuthenticatorSelection extension

Src/Fido2/Fido2.cs
Rename Fido2NetLib.cs to Fido2.cs in order to match with the class name
=> Rename Fido2NetLib.cs file to Fido2.cs in order to match with the class name

Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs
Update to the latest MDS3 BLOB url. The format of the BLOB didn't change and the root certificate to validate it neither.
=> Update to latest version of FIDO Metadata Service

BlazorWasmDemo/Client/Shared/MainLayout.razor, CHANGELOG.md, CONTRIBUTING.md, Demo/Pages/_Layout.cshtml, Demo/Pages/overview.cshtml, Demo/UrlHelperExtensions.cs, Demo/wwwroot/login.html, Src/Fido2/build/fido2.targets
Change url from `https://github.com/abergs` to `https://github.com/passwordless-lib`
=> Fix GitHub repository url

Demo/Controller.cs, Src/Fido2.Models/Objects/CredentialMakeResult.cs, Src/Fido2.Models/Objects/MakeNewCredentialResult.cs, Src/Fido2/Fido2.cs, Src/Fido2/IFido2.cs, Test/Attestation/None.cs, Test/Attestation/Packed.cs, Test/Fido2Tests.cs
=> Rename CredentialMakeResult to MakeNewCredentialResult and adjust its namespace 

Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs, Src/Fido2/Metadata/Fido2MetadataServiceRepository.cs
=> Remove hardcoded Metadata Service BLOB url to allow users to override it

Src/Fido2.Models/AuthenticatorAssertionRawResponse.cs, Src/Fido2.Models/AuthenticatorAttestationRawResponse.cs, Test/Attestation/Apple.cs, Test/AuthenticatorResponse.cs, Test/Fido2Tests.cs
Rename `AuthenticatorAttestationRawResponse.ResponseData` to `AttestationResponse` to align the naming convention of `AuthenticatorAssertionRawResponse.AssertionResponse`.
=> Rename `AuthenticatorAttestationRawResponse.ResponseData` to `AttestationResponse`

BlazorWasmDemo/Server/Controllers/UserController.cs, Demo/Controller.cs, Demo/wwwroot/js/custom.register.js, Src/Fido2.Development/StoredCredential.cs, Test/TestFiles/assertionNoneResponse.json
=> Rename `clientDataJson` to `clientDataJSON`

BlazorWasmDemo/Client/BlazorWasmDemo.Client.csproj, BlazorWasmDemo/Server/BlazorWasmDemo.Server.csproj, Demo/Demo.csproj, Directory.Build.props, Src/Fido2.AspNet/Fido2.AspNet.csproj, Src/Fido2.BlazorWebAssembly/Fido2.BlazorWebAssembly.csproj, Src/Fido2.Ctap2/Fido2.Ctap2.csproj, Src/Fido2.Development/Fido2.Development.csproj, Src/Fido2.Models/Fido2.Models.csproj, Src/Fido2/Fido2.csproj, Test/Test.csproj, Tests/Fido2.Ctap2.Tests/Fido2.Ctap2.Tests.csproj
- Set `TargetFrameworks` to `$(SupportedTargetFrameworks)`
- Align `LanguageVersion` to 11
- Set `ImplicitUsings` to `enable` in root `Directory.Build.props`
- Miscellaneous cleanup
=> Align MSBuild properties across all projects

Src/Fido2.Models/AssertionOptions.cs, Src/Fido2.Models/CredentialCreateOptions.cs
Fixes #198.
From the [spec](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialrequestoptions-timeout), for both `PublicKeyCredentialCreationOptions` and `PublicKeyCredentialRequestOptions`:
```
timeout, of type [unsigned long](https://heycam.github.io/webidl/#idl-unsigned-long)
```
So I changed the data type to `ulong`.
=> Update timeout data type to ulong

Src/Fido2/Fido2.cs, Src/Fido2/IFido2.cs, Test/Attestation/Apple.cs, Test/AuthenticatorResponse.cs, Test/Fido2Tests.cs
=> Rename `origChallenge` parameter in `Fido2.MakeNewCredentialAsync`

Demo/wwwroot/js/custom.register.js, Demo/wwwroot/js/mfa.register.js, Demo/wwwroot/js/passwordless.register.js, Demo/wwwroot/js/usernameless.register.js, Src/Fido2.BlazorWebAssembly/wwwroot/js/WebAuthn.ts, Src/Fido2.Models/AuthenticatorAttestationRawResponse.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Test/Attestation/AndroidKey.cs, Test/Attestation/AndroidSafetyNet.cs, Test/Attestation/FidoU2f.cs, Test/Attestation/Packed.cs, Test/Attestation/Tpm.cs, Test/Fido2Tests.cs
Map the authenticator transports on server side. The demo app already stores the value:
https://github.com/passwordless-lib/fido2-net-lib/blob/ebfd75d00a945a80578b27a256223122cc2aefe9/Demo/Controller.cs#L130
=> Map authenticator transports on server side

Src/Fido2.Models/Exceptions/Fido2MetadataException.cs, Src/Fido2.Models/Exceptions/Fido2VerificationException.cs, Src/Fido2.Models/UndesiredMetadataStatusFido2VerificationException.cs
Binary serialization support is no longer recommended as .NET5.0 and is obsoleted entirely in .NET 8.0 in preparation for its removal in .NET 9.0.
https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md
This PR removes binary serialization support on Exceptions (and eliminates the warnings when targeting .NET8.0) -- and helps ensure no-one relies on these when support is removed in .NET 9.0.
=> Remove binary serialization

Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/Fido2.cs, Src/Fido2/IFido2.cs
Following #447, this PR changes `List<byte[]> storedDevicePublicKeys` to `IReadOnlyList<byte[]>`.
There is no impact on the demo website as the stored credential contains a `List<byte[]>` for the device's public keys, which is compatible with `IReadOnlyList<byte[]>`.
https://github.com/passwordless-lib/fido2-net-lib/blob/528475729fe23ac68602bbd6d4e053de4b333fe5/Src/Fido2.Development/StoredCredential.cs#L51
=> Change `List<byte[]> storedDevicePublicKeys` to `IReadOnlyList<byte[]>`

Src/Fido2.BlazorWebAssembly/wwwroot/js/WebAuthn.ts, Src/Fido2.Models/AuthenticatorAttestationRawResponse.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Test/AuthenticatorResponse.cs, Test/Fido2Tests.cs
Following #474, same change has been done on `AuthenticatorAttestationRawResponse`. Additionally, the new `clientExtensionResults` is now used in `Fido2.BlazorWebAssembly` project.
@abergs, do you want me to update the demo project as well to use the new `ClientExtensionResults` prop?
=> Rename `extensions` to `clientExtensionResults`

Src/Fido2.Models/Converters/FidoEnumConverter.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Src/Fido2.Models/Objects/CredentialProtectionPolicy.cs, Test/Converters/FidoEnumConverterTests.cs
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API/WebAuthn_extensions#credprotect
https://fidoalliance.org/specs/fido-v2.2-rd-20230321/fido-client-to-authenticator-protocol-v2.2-rd-20230321.html#sctn-credProtect-extension
The input part should be okay, but does the extension output need parsing from JSON? Or should it be extracted from the `authenticator data` CBOR?
=> [Draft] Add credProtect extension to Fido2.Models

Src/Fido2.Models/AuthenticatorAssertionRawResponse.cs, Src/Fido2/AuthenticatorAssertionResponse.cs
=> Drop assertion-time attestation

Directory.Build.props, Src/Fido2.AspNet/Fido2NetLibBuilderExtensions.cs, Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Src/Fido2/Fido2.cs, Src/Fido2/IMetadataService.cs, Src/Fido2/Objects/AttestedCredentialData.cs, Src/Fido2/Objects/AuthenticatorData.cs, Src/Fido2/Objects/AuthenticatorFlags.cs, Src/Fido2/Objects/DevicePublicKeyAuthenticatorOutput.cs, Src/Fido2/Objects/Extensions.cs
=> Generate XML documentation file

Src/Fido2.Models/Objects/CredentialPropertiesOutput.cs
Based on the current editors draft on https://w3c.github.io/webauthn/ a new field `authenticatorDisplayName` has been added: https://w3c.github.io/webauthn/#dom-credentialpropertiesoutput-authenticatordisplayname
Thought it would be feasible to add this field, since it provides valuable information :)
=> Added authenticatorDisplayName to ClientPropertiesOutput

Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsLargeBlobInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsLargeBlobOutputs.cs, Src/Fido2.Models/Objects/LargeBlobSupport.cs
This PR adds support for the [`largeBlob` extension](https://www.w3.org/TR/webauthn/#sctn-large-blob-extension).
=> Add support for `largeBlob` extension

BlazorWasmDemo/Server/Controllers/UserController.cs, Demo/Controller.cs, Demo/TestController.cs, Src/Fido2.Development/StoredCredential.cs
While we might want to cache it, this is to simplify the concept so that devs more easier understand how the piecies fit toghether"
=> Resolve StoredCredential.Descriptor at access(?)

Src/Fido2/Extensions/CryptoUtils.cs, Test/CryptoUtilsTests.cs
Until further review, we've decided to revert these changes.
=> Reverting some changes

.gitignore, Demo/TestController.cs, Src/Fido2.Models/AuthenticatorAttestationRawResponse.cs, Src/Fido2.Models/CredentialCreateOptions.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Src/Fido2/AuthenticatorAssertionResponse.cs, Src/Fido2/AuthenticatorAttestationResponse.cs, Src/Fido2/AuthenticatorResponse.cs, Src/Fido2/Extensions/CryptoUtils.cs, Src/Fido2/Fido2.cs, Src/Fido2/FidoValidationMode.cs, Src/Fido2/IFido2.cs, Src/Fido2/TokenBindingDto.cs, Src/Fido2/TrustAnchor.cs, Test/AuthenticatorResponse.cs, Test/CryptoUtilsTests.cs, Test/Fido2Tests.cs, Test/Test.csproj, Test/TestFiles/metadata/256K1 U2F Authenticator anonca.json, Test/TestFiles/metadata/256K1 U2F Authenticator basic_full.json, Test/TestFiles/metadata/256K1 U2F Authenticator basic_surrogate.json, Test/TestFiles/metadata/Secp256R1 Packed Authenticator.json, Test/TestMetadataService.cs
This is based on #456 and results in a 100% pass on the v1.7.20-4 tool.
- **FIDO Conformance Tools v1.7.15 fixes**
- **Json serialization fix**
- **Unit test fix**
- **tokenbindig, AppId, UVP**
- **unit test fix (tokenbinding dto parsing)**
- **fix azure pipeline**
- **Improve trustanchor test coverage**
- **TestPackedttestationAsyncFailTrustAnchorOnRootCertInTrustPath only works on Windows**
- **Do not make this private**
- **Keep Tokenbinding around**
- **Update AuthenticatorAssertionResponse.cs**
- **Added XML comments to requestTokenBinding**
=> conformance 1.7.20 4

BlazorWasmDemo/Server/Controllers/UserController.cs, Demo/Controller.cs, Demo/TestController.cs, Src/Fido2/Fido2.cs, Src/Fido2/IFido2.cs, Src/Fido2/MakeAssertionParams.cs, Src/Fido2/MakeNewCredentialParams.cs, Tests/Fido2.Tests/Attestation/Apple.cs, Tests/Fido2.Tests/AuthenticatorResponse.cs, Tests/Fido2.Tests/ExistingU2fRegistrationDataTests.cs, Tests/Fido2.Tests/Fido2Tests.cs
Reason: In order to make arguments more readable and future API changes less likely to cause binary breaking changes to everyone we're moving many arguments into wrapping classes.
In this PR the classes are suffixed with Params, instead of popular `Options`/`Request` to avoid adding confusion as those terms are used elsewhere as part of webauthn.
=> Wrap arguments into classes

Src/Fido2/AttestationFormat/Tpm.cs
Due to what is probably a simple typo that got overlooked in the TPM spec, the manufacturer identifier assigned to IBM ended up with a lowercase 'D' character in what was supposed to be a simple ASCII to hexadecimal mapping.  This change compensates for that by trimming the `id:` portion of the TPMManufacturer string, then converting the remainder to a hex string.
By doing this, `id:49424d00` and `id:49424D00` will effectively be the same, without changing the existing static strings from the spec.
Resolves #545, where more info is available.
=> Change TPM manufacturer sting comparison handling

Src/Fido2.Models/COSETypes.cs, Src/Fido2/Objects/CredentialPublicKey.cs, Tests/Fido2.Tests/Attestation/Packed.cs, Tests/Fido2.Tests/CredentialPublicKeyTests.cs
Add test for invalid COSE key types
Add support for OKP certificates for CredentialPublicKey and test for same
Fix two packed tests that erroneously used "Reserved" key type instead of P256
Closes #552
=> Move KeyTypeParameter validation from CredentialPublicKey.Verify() into constructors

Src/Fido2.Models/CredentialCreateOptions.cs
This PR modifies the default AuthenticatorSelection configuration to discourage User Verification (UV). This change aims to improve the overall user experience for most applications where UV isn't a critical security requirement.
* Most applications don't require User Verification during signing operations
* Disabling UV by default reduces friction in the authentication flow
* Applications that need UV can still explicitly enable it
I'd appreciate community feedback on this change, particularly regarding:
* Security implications
* User experience trade-offs
* Specific use cases where this might be problematic
CC: @aseigler @iamcarbon @joegoldman2
=> AuthenticatorSelection Default to discourage UV

BlazorWasmDemo/Server/Controllers/UserController.cs, Demo/Controller.cs, Demo/TestController.cs, Src/Fido2.Models/CredentialCreateOptions.cs, Src/Fido2/Fido2.cs, Src/Fido2/GetAssertionOptionsParams.cs, Src/Fido2/IFido2.cs, Src/Fido2/RequestNewCredentialParams.cs
This PR aligns with #556 and resolves #560.
In order to let the API surface grow (e.g. introducing Hints, allow RPs to select algo's to support, etc) we want to move towards this more flexible approach.
The main downside I see is that it's harder for devs to know which arguments are the main arguments without reading docs. Not sure how to best adress that, since most arguments used are not required.
=> Introduce wrapping objects for Options-methods

Demo/TestController.cs, Src/Fido2.Models/CredentialCreateOptions.cs, Src/Fido2/Fido2.cs, Src/Fido2/RequestNewCredentialParams.cs, Tests/Fido2.Tests/Fido2Tests.cs, Tests/Fido2.Tests/TestFiles/attestationOptionsPacked.json, Tests/Fido2.Tests/TestFiles/attestationTPMSHA1Options.json
=> Allow customised pubKeyCredParams

Src/Fido2.Models/AssertionOptions.cs, Src/Fido2.Models/AuthenticatorAssertionRawResponse.cs, Src/Fido2.Models/AuthenticatorAttestationRawResponse.cs, Src/Fido2.Models/Converters/Base64UrlConverter.cs, Src/Fido2.Models/Converters/EnumNameMapper.cs, Src/Fido2.Models/Converters/FidoEnumConverter.cs, Src/Fido2.Models/CredentialCreateOptions.cs, Src/Fido2.Models/Fido2.Models.csproj, Src/Fido2.Models/Fido2Configuration.cs, Src/Fido2.Models/Metadata/BiometricStatusReport.cs, Src/Fido2.Models/Metadata/DisplayPNGCharacteristicsDescriptor.cs, Src/Fido2.Models/Metadata/MetadataBLOBPayload.cs, Src/Fido2.Models/Metadata/MetadataBLOBPayloadEntry.cs, Src/Fido2.Models/Metadata/MetadataStatement.cs, Src/Fido2.Models/Metadata/RgbPaletteEntry.cs, Src/Fido2.Models/Metadata/StatusReport.cs, Src/Fido2.Models/Metadata/UafVersion.cs, Src/Fido2.Models/Metadata/VerificationMethodDescriptor.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsClientOutputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsLargeBlobInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsLargeBlobOutputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsPRFInputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsPRFOutputs.cs, Src/Fido2.Models/Objects/AuthenticationExtensionsPRFValues.cs, Src/Fido2.Models/Objects/CredentialPropertiesOutput.cs, Src/Fido2.Models/Objects/PublicKeyCredentialUserEntity.cs, Src/Fido2.Models/Objects/RegisteredPublicKeyCredential.cs, Src/Fido2.Models/Objects/VerifyAssertionResult.cs, Src/Fido2/Metadata/ConformanceMetadataRepository.cs
This PR enables nullable for the Models project and updates a few properties in the Metadata namespace to match their nullability with specs.
=> [Models] Enable nullable (2 of 2)

Src/Fido2.BlazorWebAssembly/Fido2.BlazorWebAssembly.csproj
Turns out, release 4.0.0 didn't include the WebAssembly package. Whoops.
=> Enable packing for Fido2.BlazorWebAssembly project

.github/workflows/main.yml
Adds support for running the CI tests on Windows and macOS
platforms in addition to the existing Ubuntu runner. This
ensures the application is compatible across a wider range
of operating systems.
=> feat(ci): Add Windows and macOS runners to CI

CLAUDE.md, CONTRIBUTING.md, Demo/ConformanceTestController.cs, Demo/DemoController.cs, Demo/Pages/dashboard.cshtml, Demo/Pages/usernameless.cshtml, Demo/Properties/launchSettings.json, Demo/Startup.cs, Demo/appsettings.json, Demo/launchSettings.json, README.md, Tests/Fido2.Tests/Fido2Tests.cs
This PR moves the demo project to port 5001 and uses https. It also renames the controllers to be easier to understand.
=> Demo-project: Use HTTPS and port 5001

.github/workflows/azure-deploy.yml
This workflow deploys the demo site to azure
=> Add azure-deploy workflow
